// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tools(20180620)
// TarsParser Maintained By <WSRD> and tools Maintained By <superzheng>
// Generated from "command.tars" by Server Mode
// **********************************************************************

import * as TarsStream from "@tars/stream";

export declare namespace Command {
    class TarsDeploy {
        serverName: string;
        filebuff: TarsStream.BinBuffer;

        toObject(): TarsDeploy$OBJ;
        readFromObject(json: TarsDeploy$OBJ): void;
        toBinBuffer(): TarsStream.BinBuffer;
        static new(): TarsDeploy;
        static create(is: TarsStream.TarsInputStream): TarsDeploy;
    }
    interface TarsDeploy$OBJ {
        serverName: string;
        filebuff: Buffer;
    }

}


