// **********************************************************************
// Parsed By TarsParser(1.1.0), Generated By tools(20180620)
// TarsParser Maintained By <WSRD> and tools Maintained By <superzheng>
// Generated from "command.tars" by Imp Mode
// **********************************************************************

"use strict";

var Command = require("./command.js").Command;
module.exports.Command = Command;

